### ISSUE TITLE
🎖️ ES6 Capstone Unsplash | Setup Project 🎖️

### ISSUE THREAD

**Issue by Rysth** [Rysth/ES6-Capstone-Unsplash#22]
# 🏅 Description
_Repository Link -> https://github.com/Rysth/ES6-Capstone-Unsplash/projects/1_

## 📝 Notes

- ✅ We're actually two members John and Mohammed.

## 📷 Evidences

![image](https://github.com/Rysth/ES6-Capstone-Unsplash/assets/115722896/74be7870-0660-4693-8eb9-e0b269bed6e6)

_John Palacios & Mohammed Jamal_
_Microverse Students_

**Comment by V-Blaze** [comment]
Hi @Rysth, @mohamedgamaleldin999999  

# Approved 🍏 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![green-lantern-ok](https://user-images.githubusercontent.com/107632780/229644347-63cd2692-a569-4093-9c95-9fad40e2d9f2.gif)

 ## Highlights
- Kanban board setup correctly✔
- Board has the correct number of cards👋 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rysth** [comment]
Thanks! @V-Blaze
